### ISSUE TITLE
Log not written

### ISSUE THREAD

**Issue by Niehztog** [nvts8a/libros#28]
Hey Steve,
I just updated to v0.9.0 and can't figure out how to make libros write the logfile. Here are the contents of my `_OPENBOOK/openbook.conf` file:

```
LOG.DEBUG=1
LOG.TRUNCATE=0
```

I turned my book off and on several times, but I can't find the logfile on the sd card. What might be causing this?

**Comment by nvts8a** [comment]
I see this as well, checking it out! Thank you!

**Comment by nvts8a** [comment]
Fixed with [v0.9.1](https://github.com/nvts8a/libros/releases/tag/v0.9.1)

**Comment by Niehztog** [comment]
Thank you, that works for me 👍
